### ISSUE TITLE
Image Size Not Respected In Shortcode For Books  

### ISSUE THREAD

**Issue by dunhampa** [PippoRJ/hugo-refresh#19]
I am reproducing by building the example site.

Going to:

`<site>/content/topic_1/example_3_topic_1/
`
creating an images directory so that

`<site>/content/topic_1/example_3_topic_1/images/` 

exists.

I am copy the summary.jpg in the images just for testing.

Then I update:

`<site>/content/topic_1/example_3_topic_1/index.md`

and so that the entire file contains:

```
---
title: "Topic 1 is very cool!"
date: 2019-06-17T23:53:00+01:00
draft: true
hideLastModified: true
summary: "The summary image should be a custom one"
summaryImage: "summary.jpg"
tags: ["custom_image", "custom_summary"]
---

This is the real text of the article. 

{{< book title="Title Awesome" authors="Awesome author" image="images/summary.jpg" size="700x">}}

```

No matter what I change the size to the image on served site is very small. 

![image](https://user-images.githubusercontent.com/5845872/72313527-a0717200-3659-11ea-9304-b8b898cf9426.png)

**Comment by PippoRJ** [comment]
Hi @dunhampa ,

so here it happened that the image itself was actually resizing but the displayed size on the page was remaining the same.
(So if you change the quality to be very, e.g. using ` size="20x"`, you will see that the displayed image will have a very poor quality.)
The image size on the page is constrained to be 1/6 of the space available width and no bigger than that.

I have pushed a small change that allows the image to be smaller than the available space. I am not yet sure how can I handle the image to grow in size because I am using `columns` in Bulma (CSS framework). I will look more into it.

**Comment by PippoRJ** [comment]
I'll close the issue for the moment.
