### ISSUE TITLE
404 / page not found for included links 'about' and 'credits' on demo site

### ISSUE THREAD

**Issue by savethehousemouse** [PippoRJ/hugo-refresh#2]
I confess being a Hugo Noob. Your demo site had the best mix of features (reactive, left selection frame, top selection frame), looked very nice and your personal site built with Julia shows its power. That's why I chose it after looking at a few other options. 

Those others used toml to control the site-structure. This one utilizes yaml. The toml file duplicates the structure nicely like for example:
```
publishDir = "../public"
themesDir = "themes"
staticDir = ["../static", "static2"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Components"
    url = "/components/"
    pre = "<i class='now-ui-icons design_app'></i>"
    weight = 10
[[menu.main]]
    name = "Welcome & Start Here"
    url = "/tsr/"
    pre = "<i class='now-ui-icons design_app'></i>"
    weight = 13
[[menu.main]]
    name = "Terms of Usage"
    url = "/tou/"
    pre = "<i class='now-ui-icons design_app'></i>"
    weight = 15
``` 
etc.
I did not find where and how the left frame is defined and if there can be sub-categories like 
```
- Programming languages
--- C++
--- Python
- Web Design
--- HTML 5
--- Node JS
--- CSS
- Getting rich while staying in bed
--- Winning the Lottery
--- etc.
```

It would help enormously if you would add at least two top categories like 'about Me' and 'Hot Topics' pointing to existing pages.
At least two left side categories and last but not least two items on the bottom like 'Credits' and 'contact'.

It is much easier to dig through the control file and rename/extend the items seeing ->working<- examples and deriving their location and the syntax in the control file within the file tree.

I know it is a lot I am asking for, but without this information, I cannot build my own site through your framework and that would be a shame since it is really nice and powerful as you demonstrated on your personal site.

Thank you in advance
g strubinsky

![julia2](https://user-images.githubusercontent.com/6893610/65695230-6e6edc80-e077-11e9-927e-5612888e5a5b.png)

**Comment by PippoRJ** [comment]
Hi @savethehousemouse 

I think that your problem is that you are running Hugo, configured correctly with ReFresh, but with an empty site (i.e., an empty "content" directory).

This is the code to run the example site from scratch.
Run the following commands:
```
hugo new site myNewSite
cd myNewSite
git init
git submodule add https://github.com/PippoRJ/hugo-refresh themes/hugo-refresh
rm config.toml
cp -R themes/hugo-refresh/exampleSite/* ./
hugo server -D
```
The explanation of these commands are here:
- https://gohugo.io/getting-started/quick-start/
- README file of this theme

YAML vs TOML:
The configuration file currently follows yaml syntax but you are free to use toml if it suits more your stile. Hugo can understand both syntax.
I suggest you have a look at https://gohugohq.com/howto/toml-json-yaml-comparison/ where they compare and explain the difference between the formats. 

"I did not find where and how the left frame is defined"
--> By "left frame" do you mean left menu? I.e., the menu near the word "Tags"?
--> The left menu is done automatically reading the tags that you can define in the front matter of your articles (https://gohugo.io/content-management/front-matter/). 

"if there can be sub-categories like..."
--> You can have sub-category on the right menus. The right menu is constructed automatically as described here: https://github.com/PippoRJ/hugo-refresh/issues/1
--> Make the example site run properly and you will understand much more.
--> This theme makes use of some powerful concepts 

" 'about Me' .... 'Hot Topics' ... 'Credits' .... 'contact' "
--> At this moment the only hardcoded pages in the Theme are "About" and "Credits". All the other menus are built automatically following your content. The page "About" is show on the right menu and the "Credits" is used in the footer. There is no contact page but using the configuration "config.yaml" file you can put your email and linkedin profile. I am sure that if you run the example site correctly you will understand everything.

Let me know how it goes.
Best
Roberto
