### ISSUE TITLE
Getting error while adding summaryImage.

### ISSUE THREAD

**Issue by AndroidLibrariesYoutube** [PippoRJ/hugo-refresh#23]
While I am running command hugo server -D. It causing an error about resource.Resource.Width

```
Change detected, rebuilding site.
2020-04-10 02:03:06.136 +0530
Source changed "E:\\Personal projects\\quickstart\\content\\text\\t1.md": WRITE
WARNING: calling IsSet with unsupported type "invalid" (<nil>) will always return false.

Total in 83 ms
ERROR 2020/04/10 02:03:06 Rebuild failed:

ERROR 2020/04/10 02:03:06 Failed to render pages: render of "section" failed: execute of template failed: template: _default/list.html:25:28: executing "main" at <partial "single/summary.html" .>: error calling partial: "E:\Personal projects\quickstart\themes\hugo-refresh\layouts\partials\single\summary.html:22:32": execute of template failed: template: partials/single/summary.html:22:32: executing "partials/single/summary.html" at <$image.Width>: nil pointer evaluating resource.Resource.Width
```

```
---
title: "T1"
date: 2020-04-10T01:58:36+05:30
draft: true
summaryImage: "summary.jpg"
---
```

**Comment by PippoRJ** [comment]
Hi @AndroidLibrariesYoutube ,

have a look at https://github.com/PippoRJ/hugo-refresh/issues/6 it seems a related issue.
Where did you place the "summary.jpg" image? 
Use a leaf bundle and specify the path to the image relative to the index.md of the bundle.

Let me know if you need more help or you manged it.

**Comment by AndroidLibrariesYoutube** [comment]
Yes I have added the image in the folder. I also try to update the hugo. I also tried the leaf bundle. When I am adding your theme code in mine then it's working but when I generate a new one then it causing some issue. Do I have to do some changes in the config or other place.

**Comment by PippoRJ** [comment]
The error that you get it is the same one you were getting at the beginning or it is changed? 

Can you publish the code that you are using on GitHub? So that I can clone it and have a look.

**Comment by AndroidLibrariesYoutube** [comment]
I am getting same error as before. I am pushing the code to the repo right now.

**Comment by AndroidLibrariesYoutube** [comment]
https://github.com/AndroidLibrariesYoutube/HugoDemo

@PippoRJ You can check the repo. I am getting error on the content/posts/my-first-post.md

**Comment by PippoRJ** [comment]
Hi @AndroidLibrariesYoutube 
So there are a couple of problems.
One problem is that the folder `posts` is not a leaf bundle. To solve this problem you just need to rename the file `my-first-post.md` to `index.md`. Now, the `posts` represents an article but it is not yet inside a folder that contains articles. At this moment the article is a standalone article. To show this article in the menu use the option `showInMenu: true` (inside the `index.md`) otherwise it will not appear anywhere. 
If you want to put this article inside a folder that can contain articles, have a look at the folder `topic_2`. Inside this folder there is file called `_index.md`. If you move the folder `posts` inside this folder then this article will appear in the menu when you click under "Title of Topic 2".
Try and let me know how it goes.

**Comment by AndroidLibrariesYoutube** [comment]
@PippoRJ It worked perfectly. Thanks for your help. Be safe and Happy Coding.

**Comment by kpatnayakuni** [comment]
Hello,

Greetings!

Even, I am also in the same scenario, and still didn't understand the working concept of `summaryImage`; so if we want to use `summaryImage` do we have to create a separate leaf bundle for each post and place the images over there? 

Do we have an option to refer to a common location for the summaryImages?

And I have another doubt, what is the images folder where we can keep our images and use them inside the posts?

Thank you and appreciate your help.
