### ISSUE TITLE
linter asks... (about style.sass)

### ISSUE THREAD

**Issue by vBuresh** [PippoRJ/hugo-refresh#43]
Hi!

Thanks for the excellent theme! I like it and very glad to see how it progressing. 

When viewing the source code of the file `/themes/hugo-refreshing/assets/style.sass` linter asks to check the correctness of the block starting from line 4 (Fatal) 

! [screenshot - 87,6 kb](https://drive.google.com/file/d/1ccHoEMPoSqHKY5Q0pAsaQA1Jn5wkRKrw/view?usp=sharing)

It looks like the linter has noticed the missing quotes {{.Site.Params.mainColour}}. But you can't do that. New bugs appear.

All this does not cause damage during assembly or operation.

How to make it better? Just ignore? ))

**Comment by PippoRJ** [comment]
Hey @vBuresh ,
Thanks! 

So, the file `style.sass` is processed by hugo before been used to create the css files. Hugo will change the string `{{.Site.Params.mainColour}}` with the concrete value specified in the configuration file. The file that result from that is a file that shouldn't produce any linter problem.

If you analize the file `style.sass` before the substitution step, the linter is not able to understand why the string `{{.Site.Params.mainColour}}` is there and I guess that is the error that you encounter.

I use the same technique with the SVG images. In order to produc SVG images with the colour specified in the configuration file I modified the SVG images of the theme with the string `{{.Site.Params.mainColour}}`. This string will be substitute by hugo during the generation of the site.

Hope it helps to understand the code better.

**Comment by vBuresh** [comment]
Thanks for the detailed clarification. 

It's a pleasure to use the Hugo **ReFresh** theme designed so elegantly and professionally.

It's really great!
