### ISSUE TITLE
Google Analytics Integration

### ISSUE THREAD

**Issue by stuartlupton** [PippoRJ/hugo-refresh#48]
Hi,

Does your template have support for enabling integration with Google Analytics?

**Comment by PippoRJ** [comment]
Hey @stuartlupton ,
yes, you can add it on the `layouts/partials/counter.html` page.

**Comment by stuartlupton** [comment]
Hi @PippoRJ please can you provide some sample code to get this working?

**Comment by PippoRJ** [comment]
Hey @stuartlupton 
so you need to modify the file `layouts/partials/counter.html` of this theme.
In this file you need to place your google tracking code.

To find your google tracking code follow this:
https://support.google.com/analytics/answer/7476135?hl=en

The google tracking code it is something like:
`

<script async src="https://www.googletagmanager.com/gtag/js?id=XX-XXXXXXXXX-X"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'XX-XXXXXXXXX-X');
</script>
`
(In your google analytics you will find what to write instead of XX-XXXXXXXXX-X)

You need to copy this code in the `layouts/partials/counter.html`
