### ISSUE TITLE
hugo --minify failed with TOCSS error

### ISSUE THREAD

**Issue by dharmjit** [PippoRJ/hugo-refresh#56]
Hi, I am not sure what causes this error. I am using `Hugo Static Site Generator v0.79.1/extended windows/amd64`, hugo server command is running successfully and I am able to access the site on localhost. When I run `hugo --gc --minify`, I am getting below error.
```
Error: Error building site: TOCSS: failed to transform "style.scss" (text/x-sass): resource "sass/style.sass_7429a748998a2893dc23ed75bb2ff2ac" not found in file cache
```

Has someone faced the same error. Thanks in advance.

**Comment by PippoRJ** [comment]
Hey @dharmjit ,
I have google for the error and it seems to be a problem of `hugo` itself rather than my theme. Not 100% sure tho, please let me know if you find a solution for this.
An alternative solution to minify JS is to use the option `jsMinify: true` in the `config.yaml`.
Let me know how it goes.

**Comment by dharmjit** [comment]
@PippoRJ , I tried changing the params but it does not work. Do you think the first comment in https://discourse.gohugo.io/t/problem-chaining-tocss-and-postcss/24260 can be related to this.

**Comment by PippoRJ** [comment]
Hey @dharmjit , did you find a solution for that?
Please post it, so that other people could benefit from it.

**Comment by dharmjit** [comment]
It was a silly mistake. Some files from the other theme I was evaluating.
