### ISSUE TITLE
How to make site with this theme more performant

### ISSUE THREAD

**Issue by dharmjit** [PippoRJ/hugo-refresh#65]
Hello,

I am not sure but it seems like that the theme is a little slow. Here is my site https://goworks.netlify.app/posts/ and I have tried some netlify plugins as well for image optimization and source inlining/minimizing but it seems to not work. Any help on this.

Thanks,

**Comment by PippoRJ** [comment]
Hey @dharmjit ,
I tried to open the website multiple times during these days... A couple of times it seemed to me slightly slow but overall it seems good... I never had this issue before, so it might be a platform issue... 
I didn't explicitly add any delay in the visualisation part... so I don't know how to make it faster...

**Comment by dharmjit** [comment]
Hello @PippoRJ , I tried Google [PageSpeed](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fgoworks.netlify.app%2Fposts%2Fgo-concurrency%2Fpri-goroutines%2F) and it suggested many improvements related to unused js and css.

**Comment by PippoRJ** [comment]
Ah yes, I see what you mean... so, the theme includes many features that even if not used are still loaded.... 
To remove the unused features (js and css) depending on the content loaded is going to require quite some work... and most of the feature-dependant js and css is cached because it's static so even if I will do this work it will speedup the load of the first page while the rest is going to be pretty much the same... therefore I don't think I will ever include such optimisations... but you are very welcome to do it... it will be really impressive!
