### ISSUE TITLE
Use internal templates for Google Analytics tracking

### ISSUE THREAD

**Issue by dharmjit** [PippoRJ/hugo-refresh#69]
Hello there,

We can use Hugo internal template for Google analytics as described here https://gohugo.io/templates/internal#google-analytics. It will make this theme leaner. If it okay I can submit a PR.

**Comment by PippoRJ** [comment]
Hey @dharmjit ,
thanks for the commit, I gave the possibility to add those tracking analytics as described here https://github.com/PippoRJ/hugo-refresh#statistics-counter . You need to add the complete tracking code in  the theme path `layouts/partials/counter.html`. 
I placed it there because the google one are not the only tracking you can have. Clearly feel free the one that suits you better.

**Comment by dharmjit** [comment]
ok, that seems better. Closing this issue.
