### ISSUE TITLE
Font awesome icons not loaded

### ISSUE THREAD

**Issue by magoorden** [PippoRJ/hugo-refresh#81]
I have started using this theme, but I noticed that the font awesome icons are not shown, see screenshot below.

![Screenshot 2022-09-17 at 16 21 56](https://user-images.githubusercontent.com/36483423/190861870-d31454c3-d9a2-46ff-9224-875f55703483.png)

I can narrow the problem down to me having a subfolder as a baseURL, i.e. "https://www.example.com/root/". Some of Hugo's problems with subfolders as a root can be resolved by including `RelativeURLs: true` and `CanonifyURLs: true`, but this does not solve the missing font awesome issue.

**Comment by PippoRJ** [comment]
Hey @magoorden 
mmmmmm I see... does it work if you remove the subfolder as baseURL?

**Comment by magoorden** [comment]
Yes, it does work when I remove the subfolder. Steps to reproduce:
1. Follow your steps on https://themes.gohugo.io/themes/hugo-refresh/ to run the example site.
2. Add a subfolder to the example baseURL.
3. I cons are no longer working.

But I kind of need that subfolder, because the university provides the domain https://homes.cs.aau.dk/~martijn/ for me.

**Comment by PippoRJ** [comment]
The includes are done in the `css.html` page of the theme. 

The problem seems to be that with a subfolder in the `baseURL` then the subfolder is includes in the css files path as well... but the files are not in the that subfolder when you do `hugo server -D`...
If that is indeed the problem then when you upload the content of public folder to your own university folder the problem should solve itself because the path will be correct...
Let me know how it goes

**Comment by PippoRJ** [comment]
I solved another issue when the `BaseURL` has a subfolder... related to the homepage link in the navbar and in the footer... please pull the repo...

**Comment by magoorden** [comment]
I have run your example site (where I changed the baseURL to `https://homes.cs.aau.dk/~martijn/`) with `hugo -D` and uploaded them to https://homes.cs.aau.dk/~martijn/. As you can see, Hugo can't still figure this subfolder thing out properly...

**Comment by magoorden** [comment]
> I solved another issue when the `BaseURL` has a subfolder... related to the homepage link in the navbar and in the footer... please pull the repo...

I noticed the navigation to the home page could also be resolved by adding
```
RelativeURLs: true
CanonifyURLs: true
```
to the `config.yaml` file.

Nonetheless, I will pull your recent changes.

**Comment by PippoRJ** [comment]
the problem seems to be that the file `all.min.css` is loading urls paths from the root of the domain (this path `/webfonts/`).... and since your site is in a subfolder then is not able to load the resources correctly..

**Comment by magoorden** [comment]
I tried upgrading fontawesome to version 6 and that solved the issue with the path to `/webfonts/`. In version 6 the urls in `all.min.css` are slightly different formulated. This fixed the issue.

I created a pull request with the changes I made to fix the issue.

**Comment by PippoRJ** [comment]
Thanks that's awesome..!
I did modified the `all.min.css` because I wanted to load local resources and not remote ones.. so if that is going to load remote resources I will have to modify it again.. 
To completely solve the issue (i.e.: to be able to load local resources from correct path) you need to process that .css file in the same way I am processing the .svg files to follow the main colour scheme... not sure if you notice but the .svg files change colour when you change the main colour... that will be an amazing pull request..!

**Comment by magoorden** [comment]
The `all.min.css` file only has url fields referring to the local `/webfonts/` folder. So I think that it will not load remote resources.
I will check later whether the svg images change color (yes, I noticed it, as I changed the color for my website).

**Comment by magoorden** [comment]
> To completely solve the issue (i.e.: to be able to load local resources from correct path) you need to process that .css file in the same way I am processing the .svg files to follow the main colour scheme... not sure if you notice but the .svg files change colour when you change the main colour... that will be an amazing pull request..!

I checked the color change using your example website. I changed the `mainColour` attribute in `config.yaml` to some random color (`0b9444` to be precise), and, for example, the SVG logo in the footer nicely changes color as well without changing anything else in the code.

![Screenshot 2022-09-23 at 14 05 55](https://user-images.githubusercontent.com/36483423/191956589-ac918474-37ac-4d4a-b0c3-6dcabbc550f9.png)

**Comment by PippoRJ** [comment]
Font awesome updated to latest release, it should be fixed
